name: Build and Release APK

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:  # 添加这一行以支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # 添加 distribution 参数
          

      - name: Build APK
        run: ./gradlew assembleRelease  # 根据你的项目配置调整命令

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}  # 使用最新的 git 标签作为发布标签
          files: app/build/outputs/apk/release/app-release.apk  # APK 文件路径
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的 token
